name: CI Tests

on:
  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm i

      - name: Run ESLint
        run: npm run lint

      - name: Run Spellcheck
        run: npm run spellcheck

      - name: Run Vitest
        run: npm run ci-test

      - name: Install Playwright
        run: npx playwright install

      - name: Run Playwright
        run: npm run ci-test:e2e

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            test-results/.last-run.json
            unit-test-results/test-output.json